behavior_plugins:
  - nav2_compute_path_to_pose_action_bt_node
  - nav2_compute_path_through_poses_action_bt_node
  - nav2_follow_path_action_bt_node
  - nav2_is_stuck_condition_bt_node
  - nav2_goal_reached_condition_bt_node
  - nav2_goal_updated_condition_bt_node
  - nav2_initial_pose_received_condition_bt_node
  - nav2_reinitialize_global_localization_service_bt_node
  - nav2_rate_controller_bt_node
  - nav2_distance_controller_bt_node
  - nav2_speed_controller_bt_node
  - nav2_truncate_path_action_bt_node
  - nav2_goal_updater_node_bt_node
  - nav2_recovery_node_bt_node
  - nav2_pipeline_sequence_bt_node
  - nav2_round_robin_node_bt_node
  - nav2_transform_available_condition_bt_node
  - nav2_time_expired_condition_bt_node
  - nav2_distance_traveled_condition_bt_node
  - nav2_single_trigger_bt_node
  - nav2_is_battery_low_condition_bt_node
  - nav2_navigate_through_poses_action_bt_node
  - nav2_navigate_to_pose_action_bt_node
  - nav2_remove_passed_goals_action_bt_node
  - nav2_planner_selector_bt_node # Needed
  - nav2_controller_selector_bt_node # Needed
  - nav2_goal_checker_selector_bt_node
  - SendCommandCenterMessage
  - MoveForward
  - PatrolAction
  - CancelPatrolAction
  - TrackThreat
  - SendSmsMessage
  - SpeakerAnnouncement
  - CancelTrackThreat
  - ThreatMitigationService
  - ActivateLedService
  - ThreatDetectionConditions
  - AreSensorsReady
  - GoToHome
  - IsArucoDetected
  - ClearCostmapService
  - RecoveryActions
  - IsHandGestureDetected
  - CaptureCamera
  - IsGroupDetected
  - MoveToPeopleGroup
  - WaitForHandGesture
  - DisplayMode
  - DisplayPhoto
  - DeleteHistoryService
