velodyne_transform_node:
    ros__parameters:
        calibration: velodyne-vlp16-params.yaml
        model: VLP16
        min_range: 0.9
        max_range: 130.0
        view_direction: 0.0
        fixed_frame: "velodyne"
        target_frame: "velodyne"
        organize_cloud: true
